### PR TITLE
Expand README

### PR DESCRIPTION
**Pull request by jtheriault**
Attempting to better weave usage and installation steps together.

Added documentation for Docker image

---
This change is [Reviewable](https://reviewable.io/reviews/meltwater/awsudo/14)

### CODE REVIEW

**Comment by terodox** [comment]
*[README.md, line 4 at r1](https://reviewable.io/reviews/meltwater/awsudo/14#-LFtDuEk1WhnTUTFljF6:-LFtDuElE7txjlGiu72R:br42ckd) ([raw file](https://github.com/meltwater/awsudo/blob/f2b94fe839f7b0ccf47e1e9697bd244dcfb319e1/README.md#L4)):*
> ```Markdown
> [Build Status](https://travis-ci.org/meltwater/awsudo)
> 
> A simple utility for easily executing AWS cli commands with an assumed role.
> ```

I like the updated wording :+1: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/meltwater/awsudo/14)*

**Comment by terodox** [comment]
*[README.md, line 58 at r1](https://reviewable.io/reviews/meltwater/awsudo/14#-LFtEd7m0NTpIreeO5gt:-LFtEd7m0NTpIreeO5gu:b-2oog6n) ([raw file](https://github.com/meltwater/awsudo/blob/f2b94fe839f7b0ccf47e1e9697bd244dcfb319e1/README.md#L58)):*
> ```Markdown
> ```
> 
> ### Example usage
> ```

Should this be moved above the docker section. Maybe change the name to "Node Example Usage"

---


*Comments from [Reviewable](https://reviewable.io/reviews/meltwater/awsudo/14)*

**Comment by terodox** [comment]
@jtheriault Please see my comments.

---







*Comments from [Reviewable](https://reviewable.io/reviews/meltwater/awsudo/14#-:-LFtEpvDAEjQ9OZ9fIcb:bd92w5a)*

**Comment by jtheriault** [comment]
*[README.md, line 58 at r1](https://reviewable.io/reviews/meltwater/awsudo/14#-LFtEd7m0NTpIreeO5gt:-LFwTA_vEi7rTeRm65j9:b-mhxj4l) ([raw file](https://github.com/meltwater/awsudo/blob/f2b94fe839f7b0ccf47e1e9697bd244dcfb319e1/README.md#L58)):*
<details><summary><i>Previously, terodox (Andrew Desmarais) wrote…</i></summary><blockquote>

Should this be moved above the docker section. Maybe change the name to "Node Example Usage"
</blockquote></details>

I didn't exactly do that, but I think I embraced the spirit of your request.

---


*Comments from [Reviewable](https://reviewable.io/reviews/meltwater/awsudo/14)*

**Comment by jtheriault** [comment]
*[README.md, line 4 at r1](https://reviewable.io/reviews/meltwater/awsudo/14#-LFtDuEk1WhnTUTFljF6:-LFwTGm5Bn2QI3wBWQ1F:b-9755fn) ([raw file](https://github.com/meltwater/awsudo/blob/f2b94fe839f7b0ccf47e1e9697bd244dcfb319e1/README.md#L4)):*
<details><summary><i>Previously, terodox (Andrew Desmarais) wrote…</i></summary><blockquote>

I like the updated wording :+1: 
</blockquote></details>

Thank you!

---


*Comments from [Reviewable](https://reviewable.io/reviews/meltwater/awsudo/14)*

**Comment by terodox** [comment]
*[README.md, line 58 at r1](https://reviewable.io/reviews/meltwater/awsudo/14#-LFtEd7m0NTpIreeO5gt:-LFwf5OdDpKmVO3glHpm:bww2h7o) ([raw file](https://github.com/meltwater/awsudo/blob/f2b94fe839f7b0ccf47e1e9697bd244dcfb319e1/README.md#L58)):*
<details><summary><i>Previously, jtheriault (Joe Theriault) wrote…</i></summary><blockquote>

I didn't exactly do that, but I think I embraced the spirit of your request.
</blockquote></details>

This is an awesome update.  Thank you for taking the time to update.

---


*Comments from [Reviewable](https://reviewable.io/reviews/meltwater/awsudo/14)*

**Comment by terodox** [comment]
:lgtm: And thank you again for the awesome updates!

---







*Comments from [Reviewable](https://reviewable.io/reviews/meltwater/awsudo/14#-:-LFwfFtBC6tkNOiC9T8B:b-uwlkdz)*

**Comment by terodox** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/meltwater/awsudo/14)*

**Pull request merged**
