### PR TITLE
Deploy docker on version

### PR DESCRIPTION
**Pull request by jtheriault**
In order for a docker deploy to successfully run immediately after the version command, it needs to wait for the version to become available. This change inserts a polling loop to ensure that happens and triggers it on every version publish.

## Misc Improvements

- Updating passing `package.json` to `mustache` as the view file optoin instead of piping
- Update `deploy-docker` to pass linting with [shellcheck][shellcheck]

[shellcheck]: https://github.com/koalaman/shellcheck/

---
This change is [Reviewable](https://reviewable.io/reviews/meltwater/awsudo/49)

### CODE REVIEW

**Review by terodox — APPROVED** [review]
Thank you for addressing this!

**Review by terodox — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/meltwater/awsudo/49#-:-MawoBrW9h54pTcGbtB8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jtheriault)

**Review by mattquinlan440 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/meltwater/awsudo/49#-:-MbD9TpD0_7X1jGEzFPa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jtheriault)

**Comment by jtheriault** [comment]
For record-keeping, this resolved issue #19

**Comment by terodox** [comment]
Resolves #18

**Pull request merged**
