### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by terodox**
This change is [Reviewable](https://reviewable.io/reviews/meltwater/awsudo/2)

### CODE REVIEW

**Comment by jtheriault** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 33 at r1](https://reviewable.io:443/reviews/meltwater/awsudo/2#-L26uO3TZgHGwYLep4_b:-L26uO3UpjtrSuvUnR1i:b-jxm2ub) ([raw file](https://github.com/meltwater/awsudo/blob/b2cab46a6bb7626c63b5eab546c8385bb9e19a0f/README.md#L33)):*
> ```Markdown
> 
> 
> Modifying to test reviewable.io
> ```

Excellent test, but let's not actually merge this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/meltwater/awsudo/2)*

**Comment by jtheriault** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/meltwater/awsudo/2)*

**Comment by jtheriault** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 33 at r1](https://reviewable.io:443/reviews/meltwater/awsudo/2#-L26uO3TZgHGwYLep4_b:-L26wNtgi7tkK8OABEY4:b-n4xqpn) ([raw file](https://github.com/meltwater/awsudo/blob/b2cab46a6bb7626c63b5eab546c8385bb9e19a0f/README.md#L33)):*
<details><summary><i>Previously, jtheriault (Joe Theriault) wrote…</i></summary><blockquote>

Excellent test, but let's not actually merge this.
</blockquote></details>

Marking my disposition as "blocking" until the PR is closed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/meltwater/awsudo/2)*

**Comment by terodox** [comment]
This was a successful test of reviewable.io

**Pull request closed without merging**
