### PR TITLE
Adding a duration flag

### PR DESCRIPTION
**Pull request by rclmenezes**
I noticed that it was hard to give option aliases (e.g. "--duration" instead of "-d") with getopts, so I decided to use the popular yargs package.

At that point, I decided "why not write the whole thing in JS?" This has the added benefit that the `aws-cli` is no longer a dependency!

Let me know what you think. If it's too much for you, I can make it a normal opt.

---
This change is [Reviewable](https://reviewable.io/reviews/meltwater/awsudo/24)

### CODE REVIEW

**Comment by jtheriault** [comment]
___
*[bin/awsudo, line 46 at r1](https://reviewable.io/reviews/meltwater/awsudo/24#-Ll2KYro4SbxdeGdtm1m:-Ll2KYrp2HmQPCYvccE2:b-jm1wkv) ([raw file](https://github.com/meltwater/awsudo/blob/e2d1cb65c7dd523552c0db127312460393a529c5/bin/awsudo#L46)):*
> ```
> }
> 
> (async () => {
> ```

This requires nodejs v8 or later. Could you update .nvmrc to reflect that?

As a question, is this convention not as widespread as we believe? If not, I'll note it in the README for future contributors.

**Comment by jtheriault** [comment]
___
*[bin/awsudo, line 54 at r1](https://reviewable.io/reviews/meltwater/awsudo/24#-Ll2Qjwg6SAXpCtqTPQW:-Ll2Qjwg6SAXpCtqTPQX:b-mls7kl) ([raw file](https://github.com/meltwater/awsudo/blob/e2d1cb65c7dd523552c0db127312460393a529c5/bin/awsudo#L54)):*
> ```
>       DurationSeconds: argv.duration
>     })
>     .promise();
> ```

It would make the output more clear to handle the promise rejection here and output the error's message.

**Comment by jtheriault** [comment]
___
*[bin/awsudo, line 72 at r1](https://reviewable.io/reviews/meltwater/awsudo/24#-Ll2T5zq5-FE66ly-pQT:-Ll2T5zq5-FE66ly-pQU:b-tg4vib) ([raw file](https://github.com/meltwater/awsudo/blob/e2d1cb65c7dd523552c0db127312460393a529c5/bin/awsudo#L72)):*
> ```
> 
>   execSync(command, { stdio: "inherit" });
> })();
> ```

To prevent an UnhandledPromiseRejectionWarning, this can be trailed by a `catch` callback to set `process.exitCode`.

**Comment by jtheriault** [comment]
I love this rewrite! Thank you!

I made a few minor change requests, but we would like to incorporate this into the mainline.

After those changes, the new options will need to be documented before we cut a new version. We can address that after the merge or you can add it to this PR if you'd like to handle it yourself.

One detail regarding the documentation is that it should link to the [AWS documentation](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html) for allowable duration values, to prompt users on how to address errors from the AWS CLI.

**Comment by terodox** [comment]
We will resolve the existing build issues after this has been merged and update this PR once the newest version is published.

**Comment by terodox** [comment]
Version 1.1.0 has been pushed to both NPM and Docker - awsudo/awsudo:latest also points to v1.1.0 for now.

Let us know if you have any issues!

**Comment by terodox** [comment]
As a quick heads up, we discovered an issue after versioning that we needed to fix.  The contract for awsudo was breaking when passing additional `--params` to aws cli commands.

We noticed after the fact (oops) that you had handled this by allowing for everything after a stand-alone `--` to be used as the command, but that was a breaking change to awsudo's API.

A fix is going to be deployed shortly that will be version 1.1.1 of the package.

**Comment by rclmenezes** [comment]
Thanks, sorry about that.

**Pull request merged**
