### PR TITLE
Add verbose flag

### PR DESCRIPTION
**Pull request by terodox**
This addresses #15

---
This change is [Reviewable](https://reviewable.io/reviews/meltwater/awsudo/17)

### CODE REVIEW

**Comment by jtheriault** [comment]
Review status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @terodox and @jtheriault)

---

*[bin/awsudo, line 8 at r1](https://reviewable.io/reviews/meltwater/awsudo/17#-LGNTBhwCbVgJpUkpRe6:-LGNTBhwCbVgJpUkpRe7:b-cf44on) ([raw file](https://github.com/meltwater/awsudo/blob/e282214fa80db6ff82f83650128e1e2d734b1bc4/bin/awsudo#L8)):*
true and false is available, just be sure to exclude the [] test operator when evaluating:

> if $VERBOSE; then

---

*[bin/awsudo, line 15 at r1](https://reviewable.io/reviews/meltwater/awsudo/17#-LGNU9mZ8L4NT_sagPRm:-LGNU9mZ8L4NT_sagPRn:bn11izf) ([raw file](https://github.com/meltwater/awsudo/blob/e282214fa80db6ff82f83650128e1e2d734b1bc4/bin/awsudo#L15)):*
Is git an example of a subcommand? I think the form should be:

> awsudo [-h|--help] [-v|--verbose] \<role-arn> \<subcommand>

---

*[bin/awsudo, line 22 at r1](https://reviewable.io/reviews/meltwater/awsudo/17#-LGNVLY5Ecw3ENFX39E8:-LGNVLY5Ecw3ENFX39E9:bdlty9f) ([raw file](https://github.com/meltwater/awsudo/blob/e282214fa80db6ff82f83650128e1e2d734b1bc4/bin/awsudo#L22)):*
> ```
>     shift # past argument
>     ;;
>     *)    # unknown option
> ```

In the case of awsudo, I think the loop needs to stop in this case.

It should error (with usage info) if it's an unknown argument flag; otherwise it's a positional argument and the loop should be exited. Then $1 is the ARN and the rest is the subcommand to run with all of its arguments.

If we don't do this, we won't propagate any argument flag awsudo understands to the subcommand (which may also have a --help or --verbose option).

---

*[bin/awsudo, line 46 at r1](https://reviewable.io/reviews/meltwater/awsudo/17#-LGNUVXr58peYFXK8or4:-LGNUVXsCQDJVgQWJ9lx:b-rg5vd) ([raw file](https://github.com/meltwater/awsudo/blob/e282214fa80db6ff82f83650128e1e2d734b1bc4/bin/awsudo#L46)):*
> ```
> 
> # Report and exit if there is an error with role credentials
> if [[ "Invalid" = `node -e "try { JSON.parse(process.env.CREDENTIALS); } catch (error) { console.log('Invalid'); }"` ]]; then
> ```

oooo OW! good catch!

---


*Comments from [Reviewable](https://reviewable.io/reviews/meltwater/awsudo/17)*

**Comment by terodox** [comment]
*[bin/awsudo, line 8 at r1](https://reviewable.io/reviews/meltwater/awsudo/17#-LGNTBhwCbVgJpUkpRe6:-LGPvCNb59sMUFN5UKmq:b-oz8tyz) ([raw file](https://github.com/meltwater/awsudo/blob/e282214fa80db6ff82f83650128e1e2d734b1bc4/bin/awsudo#L8)):*
<details><summary><i>Previously, jtheriault (Joe Theriault) wrote…</i></summary><blockquote>

true and false is available, just be sure to exclude the [] test operator when evaluating:

> if $VERBOSE; then
</blockquote></details>

Good call!

---


*Comments from [Reviewable](https://reviewable.io/reviews/meltwater/awsudo/17)*

**Comment by terodox** [comment]
*[bin/awsudo, line 8 at r1](https://reviewable.io/reviews/meltwater/awsudo/17#-LGNTBhwCbVgJpUkpRe6:-LGPvMIG3ff-4m7HnME1:bt38tdu) ([raw file](https://github.com/meltwater/awsudo/blob/e282214fa80db6ff82f83650128e1e2d734b1bc4/bin/awsudo#L8)):*
<details><summary><i>Previously, terodox (Andrew Desmarais) wrote…</i></summary><blockquote>

Good call!
</blockquote></details>

Updated in faae453

---


*Comments from [Reviewable](https://reviewable.io/reviews/meltwater/awsudo/17)*

**Comment by terodox** [comment]
*[bin/awsudo, line 15 at r1](https://reviewable.io/reviews/meltwater/awsudo/17#-LGNU9mZ8L4NT_sagPRm:-LGPvcY2-mZt_u9cV9sT:b-q1umue) ([raw file](https://github.com/meltwater/awsudo/blob/e282214fa80db6ff82f83650128e1e2d734b1bc4/bin/awsudo#L15)):*
<details><summary><i>Previously, jtheriault (Joe Theriault) wrote…</i></summary><blockquote>

Is git an example of a subcommand? I think the form should be:

> awsudo [-h|--help] [-v|--verbose] \<role-arn> \<subcommand>
</blockquote></details>

Good call - Updated in 2064c2d

---


*Comments from [Reviewable](https://reviewable.io/reviews/meltwater/awsudo/17)*

**Comment by terodox** [comment]
*[bin/awsudo, line 22 at r1](https://reviewable.io/reviews/meltwater/awsudo/17#-LGNVLY5Ecw3ENFX39E8:-LGPw1Vg7SUHHkEBvcdD:b-tl3jke) ([raw file](https://github.com/meltwater/awsudo/blob/e282214fa80db6ff82f83650128e1e2d734b1bc4/bin/awsudo#L22)):*
<details><summary><i>Previously, jtheriault (Joe Theriault) wrote…</i></summary><blockquote>

In the case of awsudo, I think the loop needs to stop in this case.

It should error (with usage info) if it's an unknown argument flag; otherwise it's a positional argument and the loop should be exited. Then $1 is the ARN and the rest is the subcommand to run with all of its arguments.

If we don't do this, we won't propagate any argument flag awsudo understands to the subcommand (which may also have a --help or --verbose option).
</blockquote></details>

This is a really good point.  I've updated to allow a more logical handling of unknown options.

Update in b2ec256

---


*Comments from [Reviewable](https://reviewable.io/reviews/meltwater/awsudo/17)*

**Comment by terodox** [comment]
*[bin/awsudo, line 46 at r1](https://reviewable.io/reviews/meltwater/awsudo/17#-LGNUVXr58peYFXK8or4:-LGPwER35fTuNKX_mBv6:b-ucfknh) ([raw file](https://github.com/meltwater/awsudo/blob/e282214fa80db6ff82f83650128e1e2d734b1bc4/bin/awsudo#L46)):*
<details><summary><i>Previously, jtheriault (Joe Theriault) wrote…</i></summary><blockquote>

oooo OW! good catch!
</blockquote></details>

Thanks!

---


*Comments from [Reviewable](https://reviewable.io/reviews/meltwater/awsudo/17)*

**Comment by terodox** [comment]
*[bin/awsudo, line 22 at r1](https://reviewable.io/reviews/meltwater/awsudo/17#-LGNVLY5Ecw3ENFX39E8:-LGQ1B6v0y3Mqbl90lni:b-5amozg) ([raw file](https://github.com/meltwater/awsudo/blob/e282214fa80db6ff82f83650128e1e2d734b1bc4/bin/awsudo#L22)):*
<details><summary><i>Previously, terodox (Andrew Desmarais) wrote…</i></summary><blockquote>

This is a really good point.  I've updated to allow a more logical handling of unknown options.

Update in b2ec256
</blockquote></details>

Ok after a bit of thinking and a few experiments, I'm going to disagree with this.

The use of a subcommand with awsudo forces us to be very specific on the position of our two available options.  We need to make sure we are not stripping options from subcommands. The latest update c64af60 handles this situation.

---


*Comments from [Reviewable](https://reviewable.io/reviews/meltwater/awsudo/17)*

**Comment by terodox** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed, 4 unresolved discussions (waiting on @jtheriault)

---



*Comments from [Reviewable](https://reviewable.io/reviews/meltwater/awsudo/17)*

**Comment by jtheriault** [comment]
*[bin/awsudo, line 22 at r1](https://reviewable.io/reviews/meltwater/awsudo/17#-LGNVLY5Ecw3ENFX39E8:-LGQCdCPDib7g3XVZ4VU:b-r6wtr4) ([raw file](https://github.com/meltwater/awsudo/blob/e282214fa80db6ff82f83650128e1e2d734b1bc4/bin/awsudo#L22)):*
<details><summary><i>Previously, terodox (Andrew Desmarais) wrote…</i></summary><blockquote>

Ok after a bit of thinking and a few experiments, I'm going to disagree with this.

The use of a subcommand with awsudo forces us to be very specific on the position of our two available options.  We need to make sure we are not stripping options from subcommands. The latest update c64af60 handles this situation.
</blockquote></details>

I don't know. It looks like we agree :) this is just a more narrow and therefore tighter case. 

I'm going to confess to not recognizing the syntax checking against 0, but I'm guessing that it is validating that the index of the current position is 0. In which case I think this is a  perfectly sound solution.

---


*Comments from [Reviewable](https://reviewable.io/reviews/meltwater/awsudo/17)*

**Comment by jtheriault** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/meltwater/awsudo/17)*

**Pull request merged**
